language: docker

script:
  - |
      # build
      docker --host tcp://armard.tayloredtechnology.net:8080 build -t tayloredtechnology.azurecr.io/basal:base https://github.com/TayloredTechnology/basal.git
after_script:
  - |
      # push
      docker --host tcp://armard.tayloredtechnology.net:8080 push tayloredtechnology.azurecr.io/basal:base
