steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '-f', 'base/Dockerfile',
           '-t', 'gcr.io/taylored-technology/$REPO_NAME:base', 'base']

images:
  - 'gcr.io/taylored-technology/$REPO_NAME:base'
